[tool.poetry]
name = "manaba-attend"
version = "0.1.0"
description = "💻 コマンドラインから Manaba の出席カードを提出するプログラム"
authors = ["TAKAHASHI Shuuji <shuuji3@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4.8"
lxml = "^4.4"
pyyaml = "^5.1"
selenium = "^3.141"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
